"""Inheritance"""
import anvil.server
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables

inheritance_list = {
  "Scathach": {
    "Naoise": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 10,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Astra", "Critical", "Nihil", "Follow-Up"]
    },
    "Alec": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 10,
      "Spd": 10,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up", "Vantage"]
    },
    "Azelle": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 10,
      "Spd": 11,
      "Def": 5,
      "Lck": 1,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up"]
    },
    "Lex": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up", "Vantage"]
    },
    "Finn": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Astra", "Miracle", "Nihil", "Follow-Up"]
    },
    "Midir": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 10,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Astra", "Nihil", "Follow-Up"]
    },
    "Dew": {
      "Class": "Sword Fighter",
      "HP": 22,
      "Str": 7,
      "Mag": 0,
      "Skl": 11,
      "Spd": 12,
      "Def": 5,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up", "Sol"]
    },
    "Jamke": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Adept", "Astra", "Nihil", "Follow-Up"]
    },
    "Chulainn": {
      "Class": "Sword Fighter",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 12,
      "Spd": 12,
      "Def": 6,
      "Lck": 1,
      "Res": 0,
      "Skills": ["Follow-Up", "Nihil", "Astra", "Luna"]
    },
    "Beowolf": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Astra", "Nihil", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 7,
      "Mag": 1,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Adept", "Astra", "Critical", "Nihil", "Follow-Up"]
    },
    "Claud": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 7,
      "Mag": 1,
      "Skl": 11,
      "Spd": 12,
      "Def": 5,
      "Lck": 3,
      "Res": 2,
      "Skills": ["Astra", "Nihil", "Follow-Up"]
    }
  },
  "Larcei": {
    "Naoise": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Astra", "Critical", "Nihil", "Follow-Up"]
    },
    "Alec": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Astra", "Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up", "Vantage"]
    },
    "Azelle": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 1,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up"]
    },
    "Lex": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up", "Vantage"]
    },
    "Finn": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Astra", "Miracle", "Nihil", "Follow-Up"]
    },
    "Midir": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Astra", "Nihil", "Follow-Up"]
    },
    "Dew": {
      "Class": "Sword Fighter",
      "HP": 23,
      "Str": 7,
      "Mag": 0,
      "Skl": 11,
      "Spd": 12,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Astra", "Nihil", "Follow-Up", "Sol"]
    },
    "Jamke": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Adept", "Astra", "Nihil", "Follow-Up"]
    },
    "Chulainn": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 12,
      "Def": 6,
      "Lck": 1,
      "Res": 0,
      "Skills": ["Follow-Up", "Nihil", "Astra", "Luna"]
    },
    "Beowolf": {
      "Class": "Sword Fighter",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Astra", "Nihil", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 11,
      "Spd": 11,
      "Def": 5,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Adept", "Astra", "Critical", "Nihil", "Follow-Up"]
    },
    "Claud": {
      "Class": "Sword Fighter",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 11,
      "Spd": 12,
      "Def": 5,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Astra", "Nihil", "Follow-Up"]
    }
  },
  "Lana": {
    "Naoise": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Accost", "Critical"]
    },
    "Alec": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Vantage"]
    },
    "Azelle": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Follow-Up"]
    },
    "Lex": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 4,
      "Res": 7,
      "Skills": ["Vantage"]
    },
    "Finn": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 4,
      "Res": 7,
      "Skills": ["Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Dew": {
      "Class": "Priest",
      "HP": 22,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 4,
      "Res": 7,
      "Skills": []
    },
    "Jamke": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Accost", "Adept"]
    },
    "Chulainn": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 8,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": []
    },
    "Beowolf": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 8,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 4,
      "Res": 7,
      "Skills": ["Adept", "Critical"]
    },
    "Claud": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 9,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 4,
      "Res": 8,
      "Skills": []
    }
  },
  "Diarmuid": {
   "Naoise": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 9,
      "Mag": 0,
      "Skl": 6,
      "Spd": 6,
      "Def": 7,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Critical"]
    },
    "Alec": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 6,
      "Spd": 6,
      "Def": 7,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Vantage"]
    },
    "Azelle": {
      "Class": "Free Knight",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 6,
      "Spd": 8,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Follow-Up"]
    },
    "Lex": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 7,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Vantage"]
    },
    "Finn": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 6,
      "Spd": 7,
      "Def": 6,
      "Lck": 4,
      "Res": 0,
      "Skills": ["Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 6,
      "Spd": 8,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Dew": {
      "Class": "Free Knight",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 7,
      "Spd": 9,
      "Def": 7,
      "Lck": 5,
      "Res": 0,
      "Skills": []
    },
    "Jamke": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 7,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Accost", "Adept"]
    },
    "Chulainn": {
      "Class": "Free Knight",
      "HP": 28,
      "Str": 9,
      "Mag": 0,
      "Skl": 8,
      "Spd": 7,
      "Def": 7,
      "Lck": 1,
      "Res": 0,
      "Skills": []
    },
    "Beowolf": {
      "Class": "Free Knight",
      "HP": 27,
      "Str": 9,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 7,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Follow-Up", "Accost"]
    },
    "Lewyn": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 1,
      "Skl": 7,
      "Spd": 9,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Adept", "Critical"]
    },
    "Claud": {
      "Class": "Free Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 1,
      "Skl": 7,
      "Spd": 7,
      "Def": 6,
      "Lck": 4,
      "Res": 3,
      "Skills": []
    }
  },
  "Lester": {
    "Naoise": {
      "Class": "Arch Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 6,
      "Spd": 6,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Accost", "Critical"]
    },
    "Alec": {
      "Class": "Arch Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 6,
      "Spd": 7,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Arch Knight",
      "HP": 25,
      "Str": 7,
      "Mag": 0,
      "Skl": 6,
      "Spd": 6,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Vantage"]
    },
    "Azelle": {
      "Class": "Arch Knight",
      "HP": 23,
      "Str": 7,
      "Mag": 1,
      "Skl": 6,
      "Spd": 6,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Follow-Up"]
    },
    "Lex": {
      "Class": "Arch Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Vantage"]
    },
    "Finn": {
      "Class": "Arch Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 6,
      "Spd": 7,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Arch Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 6,
      "Spd": 6,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Dew": {
      "Class": "Arch Knight",
      "HP": 22,
      "Str": 7,
      "Mag": 0,
      "Skl": 6,
      "Spd": 7,
      "Def": 6,
      "Lck": 4,
      "Res": 0,
      "Skills": []
    },
    "Jamke": {
      "Class": "Arch Knight",
      "HP": 25,
      "Str": 7,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Accost", "Adept"]
    },
    "Chulainn": {
      "Class": "Arch Knight",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 7,
      "Lck": 2,
      "Res": 0,
      "Skills": []
    },
    "Beowolf": {
      "Class": "Arch Knight",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 7,
      "Spd": 7,
      "Def": 6,
      "Lck": 2,
      "Res": 0,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Arch Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 1,
      "Skl": 7,
      "Spd": 7,
      "Def": 6,
      "Lck": 3,
      "Res": 0,
      "Skills": ["Adept", "Critical"]
    },
    "Claud": {
      "Class": "Arch Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 2,
      "Skl": 7,
      "Spd": 7,
      "Def": 6,
      "Lck": 4,
      "Res": 2,
      "Skills": []
    }
  },
  "Fee": {
    "Naoise": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Critical", "Follow-Up"]
    },
    "Alec": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 5,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Pegasus Knight",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Follow-Up", "Vantage"]
    },
    "Azelle": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 5,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Follow-Up"]
    },
    "Lex": {
      "Class": "Pegasus Knight",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Follow-Up", "Vantage"]
    },
    "Finn": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 5,
      "Lck": 4,
      "Res": 7,
      "Skills": ["Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 5,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Dew": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 8,
      "Spd": 14,
      "Def": 5,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Follow-Up"]
    },
    "Jamke": {
      "Class": "Pegasus Knight",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Adept", "Follow-Up"]
    },
    "Chulainn": {
      "Class": "Pegasus Knight",
      "HP": 26,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Follow-Up"]
    },
    "Beowolf": {
      "Class": "Pegasus Knight",
      "HP": 25,
      "Str": 8,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 0,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Follow-Up", "Critical", "Adept"]
    },
    "Claud": {
      "Class": "Pegasus Knight",
      "HP": 24,
      "Str": 7,
      "Mag": 1,
      "Skl": 8,
      "Spd": 13,
      "Def": 6,
      "Lck": 3,
      "Res": 8,
      "Skills": ["Follow-Up"]
    }
  },
  "Arthur": {
    "Naoise": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Accost", "Critical", "Wrath"]
    },
    "Alec": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Nihil", "Follow-Up", "Wrath"]
    },
    "Arden": {
      "Class": "Mage",
      "HP": 26,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Vantage", "Wrath"]
    },
    "Azelle": {
      "Class": "Mage",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Follow-Up", "Wrath"]
    },
    "Lex": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 5,
      "Skills": ["Vantage", "Wrath"]
    },
    "Finn": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 5,
      "Skills": ["Miracle", "Follow-Up", "Wrath"]
    },
    "Midir": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Accost", "Follow-Up", "Wrath"]
    },
    "Dew": {
      "Class": "Mage",
      "HP": 23,
      "Str": 0,
      "Mag": 7,
      "Skl": 7,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Wrath"]
    },
    "Jamke": {
      "Class": "Mage",
      "HP": 26,
      "Str": 0,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Accost", "Adept", "Wrath"]
    },
    "Chulainn": {
      "Class": "Mage",
      "HP": 27,
      "Str": 1,
      "Mag": 7,
      "Skl": 9,
      "Spd": 7,
      "Def": 2,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Wrath"]
    },
    "Beowolf": {
      "Class": "Mage",
      "HP": 26,
      "Str": 1,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 5,
      "Skills": ["Accost", "Follow-Up", "Wrath"]
    },
    "Lewyn": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 8,
      "Skl": 7,
      "Spd": 8,
      "Def": 1,
      "Lck": 3,
      "Res": 5,
      "Skills": ["Adept", "Critical", "Wrath"]
    },
    "Claud": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 9,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Wrath"]
    }
  },
  "Nanna": {
    "Naoise": {
      "Class": "Troubadour",
      "HP": 25,
      "Str": 4,
      "Mag": 3,
      "Skl": 6,
      "Spd": 7,
      "Def": 3,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Accost", "Critical"]
    },
    "Alec": {
      "Class": "Troubadour",
      "HP": 24,
      "Str": 4,
      "Mag": 3,
      "Skl": 7,
      "Spd": 7,
      "Def": 3,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Troubadour",
      "HP": 25,
      "Str": 4,
      "Mag": 3,
      "Skl": 6,
      "Spd": 7,
      "Def": 3,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Vantage"]
    },
    "Azelle": {
      "Class": "Troubadour",
      "HP": 25,
      "Str": 4,
      "Mag": 3,
      "Skl": 6,
      "Spd": 7,
      "Def": 3,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Follow-Up"]
    },
    "Lex": {
      "Class": "Troubadour",
      "HP": 25,
      "Str": 4,
      "Mag": 3,
      "Skl": 7,
      "Spd": 7,
      "Def": 4,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Vantage"]
    },
    "Finn": {
      "Class": "Troubadour",
      "HP": 24,
      "Str": 4,
      "Mag": 3,
      "Skl": 7,
      "Spd": 7,
      "Def": 3,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Troubadour",
      "HP": 24,
      "Str": 4,
      "Mag": 3,
      "Skl": 6,
      "Spd": 7,
      "Def": 3,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Dew": {
      "Class": "Troubadour",
      "HP": 24,
      "Str": 4,
      "Mag": 3,
      "Skl": 7,
      "Spd": 7,
      "Def": 3,
      "Lck": 4,
      "Res": 3,
      "Skills": []
    },
    "Jamke": {
      "Class": "Troubadour",
      "HP": 25,
      "Str": 4,
      "Mag": 3,
      "Skl": 7,
      "Spd": 7,
      "Def": 3,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Accost", "Adept"]
    },
    "Chulainn": {
      "Class": "Troubadour",
      "HP": 26,
      "Str": 4,
      "Mag": 3,
      "Skl": 8,
      "Spd": 7,
      "Def": 4,
      "Lck": 3,
      "Res": 3,
      "Skills": []
    },
    "Beowolf": {
      "Class": "Troubadour",
      "HP": 26,
      "Str": 4,
      "Mag": 3,
      "Skl": 7,
      "Spd": 7,
      "Def": 3,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Follow-Up", "Accost"]
    },
    "Lewyn": {
      "Class": "Troubadour",
      "HP": 25,
      "Str": 4,
      "Mag": 3,
      "Skl": 7,
      "Spd": 8,
      "Def": 3,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Adept", "Critical"]
    },
    "Claud": {
      "Class": "Troubadour",
      "HP": 24,
      "Str": 4,
      "Mag": 4,
      "Skl": 7,
      "Spd": 7,
      "Def": 3,
      "Lck": 4,
      "Res": 4,
      "Skills": []
    }
  },
  "Patty": {
    "Naoise": {
      "Class": "Thief",
      "HP": 26,
      "Str": 5,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Accost", "Critical"]
    },
    "Alec": {
      "Class": "Thief",
      "HP": 26,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Thief",
      "HP": 26,
      "Str": 5,
      "Mag": 0,
      "Skl": 5,
      "Spd": 8,
      "Def": 2,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Vantage"]
    },
    "Azelle": {
      "Class": "Thief",
      "HP": 26,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Follow-Up"]
    },
    "Lex": {
      "Class": "Thief",
      "HP": 26,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 3,
      "Res": 1,
      "Skills": ["Vantage"]
    },
    "Finn": {
      "Class": "Thief",
      "HP": 26,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 3,
      "Res": 1,
      "Skills": ["Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Thief",
      "HP": 26,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Follow-Up", "Accost"]
    },
    "Dew": {
      "Class": "Thief",
      "HP": 24,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 3,
      "Res": 1,
      "Skills": ["Sol"]
    },
    "Jamke": {
      "Class": "Thief",
      "HP": 26,
      "Str": 5,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Accost", "Adept"]
    },
    "Chulainn": {
      "Class": "Thief",
      "HP": 27,
      "Str": 5,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 3,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Luna"]
    },
    "Beowolf": {
      "Class": "Thief",
      "HP": 26,
      "Str": 5,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 2,
      "Res": 1,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Thief",
      "HP": 26,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 3,
      "Res": 1,
      "Skills": ["Adept", "Critical"]
    },
    "Claud": {
      "Class": "Thief",
      "HP": 26,
      "Str": 4,
      "Mag": 0,
      "Skl": 5,
      "Spd": 9,
      "Def": 2,
      "Lck": 3,
      "Res": 2,
      "Skills": []
    }
  },
  "Lene": {
    "Naoise": {
      "Class": "Dancer",
      "HP": 24,
      "Str": 3,
      "Mag": 0,
      "Skl": 1,
      "Spd": 8,
      "Def": 1,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Accost", "Adept", "Critical", "Miracle"]
    },
    "Alec": {
      "Class": "Dancer",
      "HP": 24,
      "Str": 3,
      "Mag": 0,
      "Skl": 1,
      "Spd": 8,
      "Def": 1,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Adept", "Miracle", "Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Dancer",
      "HP": 25,
      "Str": 3,
      "Mag": 0,
      "Skl": 1,
      "Spd": 8,
      "Def": 1,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Adept", "Miracle", "Vantage"]
    },
    "Azelle": {
      "Class": "Dancer",
      "HP": 24,
      "Str": 3,
      "Mag": 1,
      "Skl": 1,
      "Spd": 8,
      "Def": 1,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Adept", "Miracle", "Follow-Up"]
    },
    "Lex": {
      "Class": "Dancer",
      "HP": 25,
      "Str": 3,
      "Mag": 0,
      "Skl": 2,
      "Spd": 8,
      "Def": 2,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Adept", "Miracle", "Vantage"]
    },
    "Finn": {
      "Class": "Dancer",
      "HP": 24,
      "Str": 3,
      "Mag": 0,
      "Skl": 1,
      "Spd": 8,
      "Def": 1,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Adept", "Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Dancer",
      "HP": 24,
      "Str": 3,
      "Mag": 0,
      "Skl": 1,
      "Spd": 8,
      "Def": 1,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Accost", "Adept", "Miracle", "Follow-Up"]
    },
    "Dew": {
      "Class": "Dancer",
      "HP": 24,
      "Str": 3,
      "Mag": 0,
      "Skl": 1,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 3,
      "Skills": ["Adept", "Miracle", "Sol"]
    },
    "Jamke": {
      "Class": "Dancer",
      "HP": 25,
      "Str": 3,
      "Mag": 0,
      "Skl": 2,
      "Spd": 8,
      "Def": 1,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Accost", "Adept", "Miracle"]
    },
    "Chulainn": {
      "Class": "Dancer",
      "HP": 26,
      "Str": 3,
      "Mag": 0,
      "Skl": 3,
      "Spd": 8,
      "Def": 1,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Adept", "Luna", "Miracle"]
    },
    "Beowolf": {
      "Class": "Dancer",
      "HP": 25,
      "Str": 3,
      "Mag": 0,
      "Skl": 2,
      "Spd": 8,
      "Def": 1,
      "Lck": 2,
      "Res": 3,
      "Skills": ["Accost", "Adept", "Miracle", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Dancer",
      "HP": 25,
      "Str": 3,
      "Mag": 0,
      "Skl": 2,
      "Spd": 9,
      "Def": 1,
      "Lck": 3,
      "Res": 3,
      "Skills": ["Adept", "Critical", "Miracle"]
    },
    "Claud": {
      "Class": "Dancer",
      "HP": 25,
      "Str": 3,
      "Mag": 1,
      "Skl": 2,
      "Spd": 9,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Adept", "Miracle"]
    }
  },
  "Tine": {
    "Naoise": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Accost", "Critical", "Wrath"]
    },
    "Alec": {
      "Class": "Mage",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Nihil", "Follow-Up", "Wrath"]
    },
    "Arden": {
      "Class": "Mage",
      "HP": 26,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 7,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Vantage", "Wrath"]
    },
    "Azelle": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 8,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Follow-Up", "Wrath"]
    },
    "Lex": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 2,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Vantage", "Wrath"]
    },
    "Finn": {
      "Class": "Mage",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Miracle", "Follow-Up", "Wrath"]
    },
    "Midir": {
      "Class": "Mage",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Accost", "Wrath"]
    },
    "Dew": {
      "Class": "Mage",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Wrath"]
    },
    "Jamke": {
      "Class": "Mage",
      "HP": 26,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Accost", "Adept", "Wrath"]
    },
    "Chulainn": {
      "Class": "Mage",
      "HP": 26,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Wrath"]
    },
    "Beowolf": {
      "Class": "Mage",
      "HP": 26,
      "Str": 0,
      "Mag": 7,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 5,
      "Skills": ["Accost", "Follow-Up", "Wrath"]
    },
    "Lewyn": {
      "Class": "Mage",
      "HP": 26,
      "Str": 0,
      "Mag": 8,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 6,
      "Skills": ["Adept", "Critical", "Wrath"]
    },
    "Claud": {
      "Class": "Mage",
      "HP": 25,
      "Str": 0,
      "Mag": 8,
      "Skl": 8,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 7,
      "Skills": ["Wrath"]
    }
  },
  "Febail": {
   "Naoise": {
      "Class": "Bow Fighter",
      "HP": 37,
      "Str": 12,
      "Mag": 1,
      "Skl": 14,
      "Spd": 13,
      "Def": 10,
      "Lck": 8,
      "Res": 0,
      "Skills": ["Accost", "Critical", "Follow-Up"]
    },
    "Alec": {
      "Class": "Bow Fighter",
      "HP": 36,
      "Str": 11,
      "Mag": 1,
      "Skl": 15,
      "Spd": 14,
      "Def": 8,
      "Lck": 9,
      "Res": 0,
      "Skills": ["Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Bow Fighter",
      "HP": 38,
      "Str": 13,
      "Mag": 1,
      "Skl": 13,
      "Spd": 13,
      "Def": 10,
      "Lck": 8,
      "Res": 0,
      "Skills": ["Follow-Up", "Vantage"]
    },
    "Azelle": {
      "Class": "Bow Fighter",
      "HP": 36,
      "Str": 9,
      "Mag": 4,
      "Skl": 13,
      "Spd": 15,
      "Def": 8,
      "Lck": 8,
      "Res": 0,
      "Skills": ["Follow-Up"]
    },
    "Lex": {
      "Class": "Bow Fighter",
      "HP": 37,
      "Str": 12,
      "Mag": 1,
      "Skl": 13,
      "Spd": 13,
      "Def": 9,
      "Lck": 9,
      "Res": 0,
      "Skills": ["Follow-Up", "Vantage"]
    },
    "Finn": {
      "Class": "Bow Fighter",
      "HP": 36,
      "Str": 11,
      "Mag": 1,
      "Skl": 15,
      "Spd": 14,
      "Def": 8,
      "Lck": 12,
      "Res": 0,
      "Skills": ["Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Bow Fighter",
      "HP": 35,
      "Str": 11,
      "Mag": 1,
      "Skl": 14,
      "Spd": 15,
      "Def": 8,
      "Lck": 8,
      "Res": 0,
      "Skills": ["Follow-Up", "Accost"]
    },
    "Dew": {
      "Class": "Bow Fighter",
      "HP": 33,
      "Str": 11,
      "Mag": 1,
      "Skl": 15,
      "Spd": 16,
      "Def": 9,
      "Lck": 12,
      "Res": 0,
      "Skills": ["Follow-Up"]
    },
    "Jamke": {
      "Class": "Bow Fighter",
      "HP": 38,
      "Str": 13,
      "Mag": 0,
      "Skl": 13,
      "Spd": 14,
      "Def": 9,
      "Lck": 10,
      "Res": 0,
      "Skills": ["Accost", "Adept", "Follow-Up"]
    },
    "Chulainn": {
      "Class": "Bow Fighter",
      "HP": 41,
      "Str": 12,
      "Mag": 1,
      "Skl": 19,
      "Spd": 15,
      "Def": 9,
      "Lck": 8,
      "Res": 0,
      "Skills": ["Follow-Up"]
    },
    "Beowolf": {
      "Class": "Bow Fighter",
      "HP": 38,
      "Str": 13,
      "Mag": 0,
      "Skl": 16,
      "Spd": 14,
      "Def": 9,
      "Lck": 8,
      "Res": 0,
      "Skills": ["Accost", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Bow Fighter",
      "HP": 36,
      "Str": 10,
      "Mag": 4,
      "Skl": 16,
      "Spd": 17,
      "Def": 8,
      "Lck": 9,
      "Res": 1,
      "Skills": ["Adept", "Critical", "Follow-Up"]
    },
    "Claud": {
      "Class": "Bow Fighter",
      "HP": 35,
      "Str": 9,
      "Mag": 4,
      "Skl": 14,
      "Spd": 15,
      "Def": 8,
      "Lck": 11,
      "Res": 5,
      "Skills": ["Follow-Up"]
    }
  },
  "Ced": {
    "Naoise": {
      "Class": "Sage",
      "HP": 37,
      "Str": 7,
      "Mag": 16,
      "Skl": 17,
      "Spd": 20,
      "Def": 10,
      "Lck": 5,
      "Res": 13,
      "Skills": ["Accost", "Adept", "Critical", "Follow-Up"]
    },
    "Alec": {
      "Class": "Sage",
      "HP": 36,
      "Str": 5,
      "Mag": 16,
      "Skl": 19,
      "Spd": 21,
      "Def": 8,
      "Lck": 7,
      "Res": 13,
      "Skills": ["Adept", "Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Sage",
      "HP": 40,
      "Str": 8,
      "Mag": 16,
      "Skl": 14,
      "Spd": 19,
      "Def": 4,
      "Lck": 11,
      "Res": 13,
      "Skills": ["Adept", "Follow-Up", "Vantage"]
    },
    "Azelle": {
      "Class": "Sage",
      "HP": 36,
      "Str": 2,
      "Mag": 20,
      "Skl": 15,
      "Spd": 24,
      "Def": 7,
      "Lck": 5,
      "Res": 13,
      "Skills": ["Adept", "Follow-Up"]
    },
    "Lex": {
      "Class": "Sage",
      "HP": 39,
      "Str": 7,
      "Mag": 16,
      "Skl": 16,
      "Spd": 20,
      "Def": 12,
      "Lck": 6,
      "Res": 13,
      "Skills": ["Adept", "Follow-Up", "Vantage"]
    },
    "Finn": {
      "Class": "Sage",
      "HP": 36,
      "Str": 5,
      "Mag": 16,
      "Skl": 18,
      "Spd": 21,
      "Def": 8,
      "Lck": 10,
      "Res": 13,
      "Skills": ["Adept", "Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Sage",
      "HP": 34,
      "Str": 5,
      "Mag": 16,
      "Skl": 17,
      "Spd": 23,
      "Def": 8,
      "Lck": 4,
      "Res": 13,
      "Skills": ["Accost", "Adept", "Follow-Up"]
    },
    "Dew": {
      "Class": "Sage",
      "HP": 32,
      "Str": 6,
      "Mag": 16,
      "Skl": 19,
      "Spd": 24,
      "Def": 10,
      "Lck": 10,
      "Res": 13,
      "Skills": ["Adept", "Follow-Up"]
    },
    "Jamke": {
      "Class": "Sage",
      "HP": 40,
      "Str": 5,
      "Mag": 15,
      "Skl": 15,
      "Spd": 21,
      "Def": 9,
      "Lck": 8,
      "Res": 13,
      "Skills": ["Accost", "Adept", "Follow-Up"]
    },
    "Chulainn": {
      "Class": "Sage",
      "HP": 43,
      "Str": 6,
      "Mag": 16,
      "Skl": 20,
      "Spd": 22,
      "Def": 9,
      "Lck": 5,
      "Res": 13,
      "Skills": ["Adept", "Follow-Up"]
    },
    "Beowolf": {
      "Class": "Sage",
      "HP": 38,
      "Str": 7,
      "Mag": 15,
      "Skl": 19,
      "Spd": 21,
      "Def": 9,
      "Lck": 5,
      "Res": 13,
      "Skills": ["Accost", "Adept", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Sage",
      "HP": 40,
      "Str": 2,
      "Mag": 20,
      "Skl": 19,
      "Spd": 29,
      "Def": 7,
      "Lck": 6,
      "Res": 13,
      "Skills": ["Follow-Up", "Critical", "Adept"]
    },
    "Claud": {
      "Class": "Sage",
      "HP": 37,
      "Str": 2,
      "Mag": 21,
      "Skl": 16,
      "Spd": 22,
      "Def": 7,
      "Lck": 10,
      "Res": 21,
      "Skills": ["Adept", "Follow-Up"]
    }
  },
  "Coirpre": {
    "Naoise": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Adept", "Critical", "Miracle"]
    },
    "Alec": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Adept", "Miracle", "Nihil", "Follow-Up"]
    },
    "Arden": {
      "Class": "Priest",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 6,
      "Def": 1,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Adept", "Miracle", "Vantage"]
    },
    "Azelle": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Adept", "Miracle", "Follow-Up"]
    },
    "Lex": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Adept", "Miracle", "Vantage"]
    },
    "Finn": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Adept", "Miracle", "Follow-Up"]
    },
    "Midir": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Adept", "Miracle", "Follow-Up"]
    },
    "Dew": {
      "Class": "Priest",
      "HP": 22,
      "Str": 0,
      "Mag": 7,
      "Skl": 6,
      "Spd": 8,
      "Def": 1,
      "Lck": 4,
      "Res": 7,
      "Skills": ["Adept", "Miracle"]
    },
    "Jamke": {
      "Class": "Priest",
      "HP": 25,
      "Str": 0,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Adept", "Miracle"]
    },
    "Chulainn": {
      "Class": "Priest",
      "HP": 25,
      "Str": 1,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 2,
      "Lck": 1,
      "Res": 7,
      "Skills": ["Adept", "Miracle"]
    },
    "Beowolf": {
      "Class": "Priest",
      "HP": 25,
      "Str": 1,
      "Mag": 7,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 2,
      "Res": 7,
      "Skills": ["Accost", "Adept", "Miracle", "Follow-Up"]
    },
    "Lewyn": {
      "Class": "Priest",
      "HP": 24,
      "Str": 0,
      "Mag": 8,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 7,
      "Skills": ["Adept", "Critical", "Miracle"]
    },
    "Claud": {
      "Class": "Priest",
      "HP": 23,
      "Str": 0,
      "Mag": 8,
      "Skl": 7,
      "Spd": 7,
      "Def": 1,
      "Lck": 3,
      "Res": 9,
      "Skills": ["Adept", "Miracle"]
    }
  }
}
