"""Skills"""
import anvil.server
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables

skill_list = {
  "Jacobi": ["Follow-Up"],
  "Iucharba": ["Accost"],
  "Kutuzov": ["Follow-Up"],
  "Judah": ["Follow-Up"],
  "Travant": ["Follow-Up", "Nihil"],
  "Hilda (Chronos)": ["Follow-Up"],
  "Riddell": ["Follow-Up", "Critical"],
  "Zagam": ["Follow-Up"],
  "Arvis": ["Nihil"],
  "Juphiel": ["Follow-Up"],
  "Brian": ["Follow-Up", "Accost"],
  "Hilda (Friege)": ["Follow-Up"],
  "Manfroy": ["Follow-Up"],
  "Julius": ["Accost", "Nihil"],
  "Sigurd": ["Follow-Up"],
  "Naoise": ["Critical", "Accost"],
  "Alec": ["Follow-Up", "Nihil"],
  "Azelle": ["Follow-Up"],
  "Finn": ["Follow-Up"],
  "Ethlyn": ["Critical"],
  "Midir": ["Follow-Up", "Accost"],
  "Ayra": ["Follow-Up", "Nihil"],
  "Deirdre": ["Nihil"],
  "Jamke": ["Follow-Up", "Accost"],
  "Chulainn": ["Follow-Up"],
  "Beowolf": ["Follow-Up", "Accost"],
  "Lewyn": ["Critical"],
  "Erinys": ["Follow-Up"],
  "Brigid": ["Follow-Up"],
  "Seliph": ["Follow-Up", "Nihil"],
  "Scathach": ["Follow-Up", "Nihil"],
  "Dalvin": ["Follow-Up"],
  "Larcei": ["Follow-Up", "Nihil"],
  "Creidne": ["Follow-Up"],
  "Lana": ["Accost"],
  "Diarmuid": ["Follow-Up", "Accost"],
  "Lester": ["Accost"],
  "Deimne": ["Follow-Up"],
  "Oifey": ["Follow-Up", "Critical"],
  "Julia": ["Follow-Up", "Nihil"],
  "Fee": ["Follow-Up", "Critical"],
  "Arthur": ["Follow-Up"],
  "Leif": ["Critical"],
  "Nanna": ["Follow-Up", "Accost"],
  "Shannan": ["Follow-Up"],
  "Patty": ["Follow-Up", "Accost"],
  "Ares": ["Follow-Up"],
  "Tine": ["Follow-Up"],
  "Febail": ["Follow-Up", "Accost"],
  "Asaello": ["Follow-Up", "Accost"],
  "Ced": ["Follow-Up", "Critical"],
  "Hawk": ["Follow-Up"],
  "Altena": ["Critical"]
}
